[package]
name = "gitv"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
anyhow = "1.0"
gix = "0.76"
ratatui = { version = "0.30", features = ["crossterm_0_29"] }
crossterm = "0.29"
clap = "4.1"
color-eyre = "0.6"